
-- ~/.config/wallust/templates/nvchad.lua
-- This is a Base46-compatible theme table generated by wallust

local M = {}

M.base_30 = {
  white         = "#F6ECE0",
  black         = "#000004",
  darker_black  = "#000004",
  black2        = "#A39A8D",
  one_bg        = "#000004",
  one_bg2       = "#A39A8D",
  one_bg3       = "#A39A8D",
  grey          = "#A39A8D",
  grey_fg       = "#EADCCA",
  grey_fg2      = "#EADCCA",
  light_grey    = "#EADCCA",

  red           = "#3D3D49",
  baby_pink     = "#95A4AA",
  pink          = "#95A4AA",
  line          = "#A39A8D",

  green         = "#406E8A",
  vibrant_green = "#406E8A",

  blue          = "#C48369",
  nord_blue     = "#C48369",

  yellow        = "#807379",
  sun           = "#807379",

  purple        = "#95A4AA",
  dark_purple   = "#95A4AA",

  teal          = "#E5CAA6",
  orange        = "#3D3D49",
  cyan          = "#E5CAA6",

  statusline_bg = "#000004",
  lightbg       = "#000004",
  pmenu_bg      = "#406E8A",
  folder_bg     = "#C48369",
}

M.base_16 = {
  base00 = "#000004",
  base01 = "#000004",
  base02 = "#A39A8D",
  base03 = "#EADCCA",
  base04 = "#EADCCA",
  base05 = "#F6ECE0",
  base06 = "#F6ECE0",
  base07 = "#EADCCA",
  base08 = "#3D3D49",
  base09 = "#3D3D49",
  base0A = "#807379",
  base0B = "#406E8A",
  base0C = "#E5CAA6",
  base0D = "#C48369",
  base0E = "#95A4AA",
  base0F = "#95A4AA",
}

M.type = "dark"

M = require("base46").override_theme(M, "nvchad_wallust")
return M
